### ISSUE TITLE
Gruvbox Example in my workflow

### ISSUE THREAD

**Issue by mTvare6** [Jean-Tinland/simple-bar-website#1]
![image](https://user-images.githubusercontent.com/57838468/116786786-308d3200-aabe-11eb-90ab-8ad145887765.png)

**Comment by Jean-Tinland** [comment]
Thanks, I added your screen in the website gallery!

**Comment by mTvare6** [comment]
@Jean-Tinland more of a question, do you use a custom daemon for notifications in macOS like in your website
![image](https://user-images.githubusercontent.com/57838468/117531378-d7faef00-afff-11eb-9f8d-0cd1cbdb84b8.png)

**Comment by Jean-Tinland** [comment]
Hi!

Nope this is simply a fake notification illustrating the real simple-bar behaviour on desktop :)
