### ISSUE TITLE
Option to display seconds in time widget

### ISSUE THREAD

**Issue by sputtene** [Jean-Tinland/simple-bar-website#2]
Hi,

Is it possible to add an option to display seconds in the time widget?

I have been looking at the code and I might be able to add it myself (I'll send a pull request if I succeed), but I'm not really fluent in JavaScript, so it might take a while.

Thanks for your awesome yabai-aware status bar!
Sven

**Comment by Jean-Tinland** [comment]
Hi ! I'm glad you like it! 

I just added a 'showSeconds' option in time widget settings :)

**Comment by sputtene** [comment]
Thank you sir, you are awesome! :D
